language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.14"

install:
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-tests --cover-package=pyx12 --cover-erase

after_success:
    - coveralls
